### ISSUE TITLE
Problem with `as.data.frame` with `emmGrid` objects

### ISSUE THREAD

**Issue by rvlenth** [bozenne/LMMstar#2]
Hello,

I ran into a snag with the **LMMstar** package with my latest update.  In emmeans version 1.8.0, I had changed `as.data.frame()` to return an object of class `summary_emm`, so that the annotations still are visible. I did this because I get a lot of questions from people who used `as.data.frame` and then didn't see the messages that would have cleared up their question had they seen them. A `summary_emm` object is still a data frame, so that shouldn't cause problems. -- And it didn't until my latest update.

What happened with my latest update is that I also changed the way the `[` operator works so that we retain the `summary_emm` class whenever possible. The snag is in your method `dummy.coef.lmm`, in which the object `out` (which is the returned object) is now a `summary_emm` object. You change the names of all the columns and also change `attr(out, "estName")` to `NULL`. That creates a problem because when `out` is returned and displayed, it goes through `print.summary_emm` which requires that attribute to be present.

I'm going to try to robustify my package code so it can get past that; but my suggestion is that in your next update, you return `data.frame(out)`. Doing so also nulls-out all those attributes that you manually nulled-out in your code.

**Comment by bozenne** [comment]
Thanks for your suggestion and the explanations. I have update accordingly (actually almost I put as.data.frame instead of data.frame but that should achieve the same). I think that should be good now.

**Comment by rvlenth** [comment]
There is a difference though: as.data.frame retains the attributes. data.frame removes them.

Sent from my iPhone

On Sep 10, 2022, at 2:11 PM, Ozenne ***@***.***> wrote:

﻿

Thanks for your suggestion and the explanations. I have update accordingly (actually almost I put as.data.frame instead of data.frame but that should achieve the same). I think that should be good now.
